spring.application.name=blog-app

# 一時的にデータベースを使わずに、Webの画面や他のロジックだけの動作確認をしたい
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
# Spring Boot が接続を供給する DataSource を自動で組み立てます。
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/tasks
spring.datasource.username=root
spring.datasource.password=root